version: '3.9'

services:
  cassandra:
    image: cassandra:4.1.5
    container_name: cassandraDbDockerCompose
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=RAC1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    volumes:
      - cassandra_data:/var/lib/cassandra
    networks:
      - cassandra_net

volumes:
  cassandra_data:

networks:
  cassandra_net:
    driver: bridge